-- Lo schema come lo aveva costruito Hibernate fino ad agosto 2026.
-- Da qui in poi ogni cambiamento passa da un file nuovo in questa cartella:
-- si vede cosa e' successo, e si puo' rifare uguale su un altro database.

CREATE TABLE attivita_fornitore (
    profilo_fornitore_id bigint NOT NULL,
    attivita_servizio_id bigint NOT NULL
);

CREATE TABLE attivita_servizio (
    id bigint NOT NULL,
    nome character varying(120) NOT NULL,
    categoria_id bigint NOT NULL
);

ALTER TABLE attivita_servizio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME attivita_servizio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE candidature (
    id bigint NOT NULL,
    data_creazione timestamp(6) without time zone,
    messaggio text,
    prezzo_offerto numeric(10,2),
    stato character varying(20) NOT NULL,
    profilo_fornitore_id bigint NOT NULL,
    richiesta_id bigint NOT NULL,
    CONSTRAINT candidature_stato_check CHECK (((stato)::text = ANY ((ARRAY['IN_ATTESA'::character varying, 'ACCETTATA'::character varying, 'RIFIUTATA'::character varying])::text[])))
);

ALTER TABLE candidature ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME candidature_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE categorie_fornitore (
    profilo_fornitore_id bigint NOT NULL,
    categoria_servizio_id bigint NOT NULL
);

CREATE TABLE categorie_servizio (
    id bigint NOT NULL,
    nome character varying(80) NOT NULL
);

ALTER TABLE categorie_servizio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME categorie_servizio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE incarichi (
    id bigint NOT NULL,
    data_completamento timestamp(6) without time zone,
    data_creazione timestamp(6) without time zone,
    prezzo_concordato numeric(10,2),
    stato character varying(20) NOT NULL,
    profilo_fornitore_id bigint NOT NULL,
    richiesta_id bigint NOT NULL,
    CONSTRAINT incarichi_stato_check CHECK (((stato)::text = ANY ((ARRAY['ASSEGNATO'::character varying, 'IN_CORSO'::character varying, 'COMPLETATO'::character varying, 'ANNULLATO'::character varying])::text[])))
);

ALTER TABLE incarichi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME incarichi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE luoghi (
    id bigint NOT NULL,
    cercato character varying(300) NOT NULL,
    citta character varying(120),
    data_creazione timestamp(6) without time zone,
    indirizzo character varying(400) NOT NULL,
    latitudine double precision NOT NULL,
    longitudine double precision NOT NULL
);

ALTER TABLE luoghi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME luoghi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE profili_fornitore (
    id bigint NOT NULL,
    data_approvazione timestamp(6) without time zone,
    data_creazione timestamp(6) without time zone,
    descrizione text,
    stato character varying(20) NOT NULL,
    zona_operativa character varying(255),
    utente_id bigint NOT NULL,
    tipo character varying(20),
    tariffa_oraria numeric(10,2),
    termini_accettati boolean DEFAULT false,
    latitudine double precision,
    longitudine double precision,
    motivo_rifiuto character varying(300),
    CONSTRAINT profili_fornitore_stato_check CHECK (((stato)::text = ANY ((ARRAY['IN_ATTESA'::character varying, 'APPROVATO'::character varying, 'RIFIUTATO'::character varying])::text[]))),
    CONSTRAINT profili_fornitore_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PROFESSIONISTA'::character varying, 'HOBBISTA'::character varying])::text[])))
);

ALTER TABLE profili_fornitore ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME profili_fornitore_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE recensioni (
    id bigint NOT NULL,
    commento text,
    data_creazione timestamp(6) without time zone,
    voto integer NOT NULL,
    incarico_id bigint NOT NULL,
    CONSTRAINT recensioni_voto_check CHECK (((voto >= 1) AND (voto <= 5)))
);

ALTER TABLE recensioni ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME recensioni_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE richieste_servizio (
    id bigint NOT NULL,
    budget numeric(10,2),
    citta character varying(120) NOT NULL,
    data_creazione timestamp(6) without time zone,
    data_preferita date,
    descrizione text NOT NULL,
    stato character varying(20) NOT NULL,
    titolo character varying(150) NOT NULL,
    categoria_id bigint NOT NULL,
    cliente_id bigint NOT NULL,
    fornitore_richiesto_id bigint,
    attivita_id bigint,
    indirizzo character varying(300),
    latitudine double precision,
    longitudine double precision,
    data_entro date,
    CONSTRAINT richieste_servizio_stato_check CHECK (((stato)::text = ANY ((ARRAY['APERTA'::character varying, 'ASSEGNATA'::character varying, 'COMPLETATA'::character varying, 'ANNULLATA'::character varying])::text[])))
);

ALTER TABLE richieste_servizio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME richieste_servizio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE tariffe_fornitore (
    id bigint NOT NULL,
    tariffa_oraria numeric(10,2) NOT NULL,
    categoria_id bigint NOT NULL,
    profilo_fornitore_id bigint NOT NULL
);

ALTER TABLE tariffe_fornitore ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tariffe_fornitore_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE utenti (
    id bigint NOT NULL,
    citta character varying(255),
    data_creazione timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    hash_password character varying(255) NOT NULL,
    nome_completo character varying(255) NOT NULL,
    telefono character varying(255),
    motivo_sospensione character varying(300),
    sospeso boolean DEFAULT false
);

ALTER TABLE utenti ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME utenti_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY attivita_fornitore
    ADD CONSTRAINT attivita_fornitore_pkey PRIMARY KEY (profilo_fornitore_id, attivita_servizio_id);

ALTER TABLE ONLY attivita_servizio
    ADD CONSTRAINT attivita_servizio_pkey PRIMARY KEY (id);

ALTER TABLE ONLY candidature
    ADD CONSTRAINT candidature_pkey PRIMARY KEY (id);

ALTER TABLE ONLY categorie_fornitore
    ADD CONSTRAINT categorie_fornitore_pkey PRIMARY KEY (profilo_fornitore_id, categoria_servizio_id);

ALTER TABLE ONLY categorie_servizio
    ADD CONSTRAINT categorie_servizio_pkey PRIMARY KEY (id);

ALTER TABLE ONLY incarichi
    ADD CONSTRAINT incarichi_pkey PRIMARY KEY (id);

ALTER TABLE ONLY luoghi
    ADD CONSTRAINT luoghi_pkey PRIMARY KEY (id);

ALTER TABLE ONLY profili_fornitore
    ADD CONSTRAINT profili_fornitore_pkey PRIMARY KEY (id);

ALTER TABLE ONLY recensioni
    ADD CONSTRAINT recensioni_pkey PRIMARY KEY (id);

ALTER TABLE ONLY richieste_servizio
    ADD CONSTRAINT richieste_servizio_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tariffe_fornitore
    ADD CONSTRAINT tariffe_fornitore_pkey PRIMARY KEY (id);

ALTER TABLE ONLY utenti
    ADD CONSTRAINT uk9b90mk1nolf3ou90p42a93tjo UNIQUE (email);

ALTER TABLE ONLY categorie_servizio
    ADD CONSTRAINT ukbj3jyh8vnnf82eb5ov6b9f4vg UNIQUE (nome);

ALTER TABLE ONLY incarichi
    ADD CONSTRAINT ukesvwmg9wgxggj9wixmaxn63vp UNIQUE (richiesta_id);

ALTER TABLE ONLY profili_fornitore
    ADD CONSTRAINT ukfnd84bhn9cbxk7c3bv2ndye7q UNIQUE (utente_id);

ALTER TABLE ONLY tariffe_fornitore
    ADD CONSTRAINT uki90tyfgqxmw5vpxyrf5gjg9cu UNIQUE (profilo_fornitore_id, categoria_id);

ALTER TABLE ONLY luoghi
    ADD CONSTRAINT ukiybuwhuc737h3j39vdwaxhid4 UNIQUE (cercato);

ALTER TABLE ONLY candidature
    ADD CONSTRAINT ukm726n7o72rnbvny3n3063fd1i UNIQUE (richiesta_id, profilo_fornitore_id);

ALTER TABLE ONLY recensioni
    ADD CONSTRAINT ukrjfns6bsdx94wqdjregyttrdx UNIQUE (incarico_id);

ALTER TABLE ONLY utenti
    ADD CONSTRAINT utenti_pkey PRIMARY KEY (id);

ALTER TABLE ONLY candidature
    ADD CONSTRAINT fk659fp8y4nbi4och0faykijw5d FOREIGN KEY (profilo_fornitore_id) REFERENCES profili_fornitore(id);

ALTER TABLE ONLY attivita_fornitore
    ADD CONSTRAINT fk7jkbci54c1odkhk36xgi27sr FOREIGN KEY (profilo_fornitore_id) REFERENCES profili_fornitore(id);

ALTER TABLE ONLY richieste_servizio
    ADD CONSTRAINT fk7rmwp2gtwliykrpmeedhyntd9 FOREIGN KEY (attivita_id) REFERENCES attivita_servizio(id);

ALTER TABLE ONLY candidature
    ADD CONSTRAINT fk96c01ibxxa9y1sv3emu8jisw1 FOREIGN KEY (richiesta_id) REFERENCES richieste_servizio(id);

ALTER TABLE ONLY profili_fornitore
    ADD CONSTRAINT fka73lpwj6bnusb14k5uogrhbqr FOREIGN KEY (utente_id) REFERENCES utenti(id);

ALTER TABLE ONLY tariffe_fornitore
    ADD CONSTRAINT fkah1btyegnv7bwgsnhior76su8 FOREIGN KEY (profilo_fornitore_id) REFERENCES profili_fornitore(id);

ALTER TABLE ONLY tariffe_fornitore
    ADD CONSTRAINT fkb3ce1s6iufpbetd6bvy60qhrn FOREIGN KEY (categoria_id) REFERENCES categorie_servizio(id);

ALTER TABLE ONLY richieste_servizio
    ADD CONSTRAINT fkbv93nr569ci572dy9a70m5i41 FOREIGN KEY (fornitore_richiesto_id) REFERENCES profili_fornitore(id);

ALTER TABLE ONLY richieste_servizio
    ADD CONSTRAINT fkcqnt40fhchtw38bwol14pwqsq FOREIGN KEY (categoria_id) REFERENCES categorie_servizio(id);

ALTER TABLE ONLY incarichi
    ADD CONSTRAINT fkfqonh67n23nrfngkrm78fsgab FOREIGN KEY (profilo_fornitore_id) REFERENCES profili_fornitore(id);

ALTER TABLE ONLY attivita_fornitore
    ADD CONSTRAINT fkg71xawrj1ajr2yqple83wk5ha FOREIGN KEY (attivita_servizio_id) REFERENCES attivita_servizio(id);

ALTER TABLE ONLY attivita_servizio
    ADD CONSTRAINT fkgpfi73rn1hjge20edj8vyutde FOREIGN KEY (categoria_id) REFERENCES categorie_servizio(id);

ALTER TABLE ONLY incarichi
    ADD CONSTRAINT fkh986uigk7ysywemtlfk4ycj5s FOREIGN KEY (richiesta_id) REFERENCES richieste_servizio(id);

ALTER TABLE ONLY categorie_fornitore
    ADD CONSTRAINT fkk6r8wgaoi4d5fqugb6232q5e0 FOREIGN KEY (categoria_servizio_id) REFERENCES categorie_servizio(id);

ALTER TABLE ONLY categorie_fornitore
    ADD CONSTRAINT fkkg7084rh5r914chs9k0ntuql4 FOREIGN KEY (profilo_fornitore_id) REFERENCES profili_fornitore(id);

ALTER TABLE ONLY recensioni
    ADD CONSTRAINT fkkwpucte7rcm2o6awrtm0f7l9q FOREIGN KEY (incarico_id) REFERENCES incarichi(id);

ALTER TABLE ONLY richieste_servizio
    ADD CONSTRAINT fkobs5xgeq7vbmiooca5et68waa FOREIGN KEY (cliente_id) REFERENCES utenti(id);
