-- Le foto di una richiesta. Il file vero sta nell'archivio (disco o bucket):
-- qui resta solo la chiave per ritrovarlo e chi l'ha caricato.

CREATE TABLE foto (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chiave character varying(200) NOT NULL UNIQUE,
    tipo character varying(40) NOT NULL,
    dimensione bigint NOT NULL,
    richiesta_id bigint NOT NULL REFERENCES richieste_servizio (id),
    caricata_da_id bigint NOT NULL REFERENCES utenti (id),
    data_creazione timestamp(6) without time zone
);

-- si cercano sempre per richiesta
CREATE INDEX idx_foto_richiesta ON foto (richiesta_id);
