CREATE TABLE IF NOT EXISTS fasce_disponibilita (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profilo_fornitore_id bigint NOT NULL REFERENCES profili_fornitore (id),
    giorno character varying(12) NOT NULL,
    dalle time without time zone NOT NULL,
    alle time without time zone NOT NULL,
    CONSTRAINT fasce_giorno_check CHECK (giorno IN
        ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')),
    CONSTRAINT fasce_orario_check CHECK (alle > dalle)
);

CREATE INDEX IF NOT EXISTS idx_fasce_profilo ON fasce_disponibilita (profilo_fornitore_id);

CREATE TABLE IF NOT EXISTS assenze (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profilo_fornitore_id bigint NOT NULL REFERENCES profili_fornitore (id),
    dal date NOT NULL,
    al date NOT NULL,
    motivo character varying(200),
    CONSTRAINT assenze_periodo_check CHECK (al >= dal)
);

CREATE INDEX IF NOT EXISTS idx_assenze_profilo ON assenze (profilo_fornitore_id);
