-- Quando un Tasker lavora, e quando non c'e'.
-- Piu' righe sullo stesso giorno fanno piu' fasce: mattina e pomeriggio.

CREATE TABLE fasce_disponibilita (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profilo_fornitore_id bigint NOT NULL REFERENCES profili_fornitore (id),
    giorno character varying(12) NOT NULL,
    dalle time without time zone NOT NULL,
    alle time without time zone NOT NULL,
    CONSTRAINT fasce_giorno_check CHECK (giorno IN
        ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')),
    -- una fascia che finisce prima di cominciare non vuol dire niente
    CONSTRAINT fasce_orario_check CHECK (alle > dalle)
);

CREATE INDEX idx_fasce_profilo ON fasce_disponibilita (profilo_fornitore_id);

CREATE TABLE assenze (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profilo_fornitore_id bigint NOT NULL REFERENCES profili_fornitore (id),
    dal date NOT NULL,
    al date NOT NULL,
    motivo character varying(200),
    CONSTRAINT assenze_periodo_check CHECK (al >= dal)
);

CREATE INDEX idx_assenze_profilo ON assenze (profilo_fornitore_id);
