CREATE TABLE conversazioni (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incarico_id bigint NOT NULL UNIQUE,
    data_creazione timestamp(6) without time zone NOT NULL,
    CONSTRAINT conversazioni_incarico_fk FOREIGN KEY (incarico_id) REFERENCES incarichi(id)
);

CREATE TABLE messaggi (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversazione_id bigint NOT NULL,
    autore_id bigint NOT NULL,
    testo text NOT NULL,
    data_creazione timestamp(6) without time zone NOT NULL,
    CONSTRAINT messaggi_conversazione_fk FOREIGN KEY (conversazione_id) REFERENCES conversazioni(id),
    CONSTRAINT messaggi_autore_fk FOREIGN KEY (autore_id) REFERENCES utenti(id),
    CONSTRAINT messaggi_testo_check CHECK (length(btrim(testo)) between 1 and 2000)
);

CREATE INDEX messaggi_conversazione_data_idx ON messaggi (conversazione_id, data_creazione, id);
