spring.application.name=tasky

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/tasky
spring.datasource.username=tasky
spring.datasource.password=tasky

# In sviluppo Hibernate allinea da solo le tabelle alle entita
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
